-- Create gallery table
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  display_order INT DEFAULT 0,
  category TEXT DEFAULT 'General',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ensure category column exists if table was already created
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='gallery' AND column_name='category') THEN
    ALTER TABLE public.gallery ADD COLUMN category TEXT DEFAULT 'General';
  END IF;
END $$;

-- RLS for gallery
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- Reading policy
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Lectura pública de galería') THEN
    CREATE POLICY "Lectura pública de galería" ON public.gallery FOR SELECT USING (true);
  END IF;
END $$;

-- Upload policy for admins
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin gestiona galería') THEN
    CREATE POLICY "Admin gestiona galería" ON public.gallery FOR ALL USING (
      EXISTS (
        SELECT 1 FROM profiles 
        WHERE profiles.id = auth.uid() 
        AND (profiles.role = 'admin' OR profiles.role = 'superadmin')
      )
    );
  END IF;
END $$;

-- Storage bucket for gallery
INSERT INTO storage.buckets (id, name, public) 
VALUES ('gallery', 'gallery', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Gallery') THEN
    CREATE POLICY "Public Access Gallery" ON storage.objects FOR SELECT USING (bucket_id = 'gallery');
  END IF;
END $$;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can upload to gallery') THEN
    CREATE POLICY "Admins can upload to gallery" ON storage.objects FOR INSERT WITH CHECK (
      bucket_id = 'gallery' AND 
      EXISTS (
        SELECT 1 FROM profiles 
        WHERE profiles.id = auth.uid() 
        AND (profiles.role = 'admin' OR profiles.role = 'superadmin')
      )
    );
  END IF;
END $$;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can delete from gallery') THEN
    CREATE POLICY "Admins can delete from gallery" ON storage.objects FOR DELETE USING (
      bucket_id = 'gallery' AND 
      EXISTS (
        SELECT 1 FROM profiles 
        WHERE profiles.id = auth.uid() 
        AND (profiles.role = 'admin' OR profiles.role = 'superadmin')
      )
    );
  END IF;
END $$;
